GenerateRecommendations:
  image:
    name: lambdaimage
    command: ["src.functions.optimizer.generate_recommendations.handler"]
  memorySize: 1024
  timeout: 900
  iamRoleStatementsName: ${self:service}-${self:custom.stage}-GenerateRecommendations-lambdaRole
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: "*"
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "arn:aws:logs:*:*:*"
  events:
    - schedule:
        # 6h UTC-3 = 9h UTC
        rate: cron(0 9 * * ? *)
        enabled: true
        input:
          source: "daily_optimization"
    - http:
        path: optimizer
        method: post
        cors: true

ApplyRecommendations:
  image:
    name: lambdaimage
    command: ["src.functions.optimizer.apply_recommendations.handler"]
  memorySize: 1024
  timeout: 300
  iamRoleStatementsName: ${self:service}-${self:custom.stage}-ApplyRecommendations-lambdaRole
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: "*"
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "arn:aws:logs:*:*:*"
  events:
    - http:
        path: optimizer/apply/{googleCampaignId}
        method: post
        cors: true