Resources:
  ScheduledRemindersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.resourcePrefix}-scheduled-reminders
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: sendAt
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: status-sendAt-index
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: sendAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
