Resources:
  ExecutionHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.resourcePrefix}-execution-history
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: traceId
          AttributeType: S
        - AttributeName: stageTm
          AttributeType: S
        - AttributeName: stage
          AttributeType: S
      KeySchema:
        - AttributeName: traceId
          KeyType: HASH
        - AttributeName: stageTm
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: traceId-stage-index
          KeySchema:
            - AttributeName: traceId
              KeyType: HASH
            - AttributeName: stage
              KeyType: RANGE
          Projection:
            ProjectionType: ALL 