CampaignOrchestrator:
  image:
    name: lambdaimage
    command: ["src.functions.campaign.orchestrator.handler"]
  memorySize: 512
  iamRoleStatementsName: ${self:service}-${self:custom.stage}-CampaignOrchestrator-lambdaRole
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "arn:aws:logs:*:*:*"

CampaignRecorder:
  image:
    name: lambdaimage
    command: ["src.functions.campaign.recorder.handler"]
  memorySize: 512
  iamRoleStatementsName: ${self:service}-${self:custom.stage}-CampaignRecorder-lambdaRole
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "arn:aws:logs:*:*:*"

MccStatusChecker:
  image:
    name: lambdaimage
    command: ["src.functions.campaign.mcc_status_checker.handler"]
  memorySize: 512
  timeout: 300
  iamRoleStatementsName: ${self:service}-${self:custom.stage}-MccStatusChecker-lambdaRole
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "arn:aws:logs:*:*:*"
  events:
    - schedule:
        rate: rate(5 minutes)
        enabled: true
        input:
          source: "scheduled_check"
