PayloadParser:
  image:
    name: lambdaimage
    command: ["src.functions.parser.parser.handler"]
  memorySize: 512
  iamRoleStatementsName: ${self:service}-${self:custom.stage}-PayloadParser-lambdaRole
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "arn:aws:logs:*:*:*"
